-- INSERT INTO courses (id, name, description) VALUES (1,'Maths101', 'Basic Mathematics');
-- INSERT INTO courses (id, name, description) VALUES (2,'Maths201', 'Advanced Mathematics');
-- INSERT INTO courses (id, name, description) VALUES (3,'Physics101', 'Basic Physics');
-- INSERT INTO courses (id, name, description) VALUES (4,'Physics201', 'Advanced Physics');